### ISSUE TITLE
Support AnyValue?

### ISSUE THREAD

**Issue by pcboy** [Jane-Terziev/dry-swagger#4]
In my contract sometimes I need to support "AnyObject" basically, as I don't know necessarily the format of what will be given to me beforehand. I just want to store what I'm being given.

So I have this:

```ruby
class Contracts::Sensors::NewContract < Dry::Validation::Contract
  params do
    required(:name).filled(:string)
    optional(:metadata).hash
  end

  def to_swagger
    Dry::Swagger::DocumentationGenerator.new.from_validation(self.class)
  end
end
```

Sadly if I call `Contracts::Sensors::NewContract.new.to_swagger`

I get:

```
StandardError: Could not generate documentation for field metadata. The field is defined as hash,
          but the schema is not defined.
          Valid types are: ["string", "integer", "boolean", "float", "decimal", "datetime", "date", "time", "uuid"].
          The parser has generated the following definition for the field: metadata: {:required=>false, :type=>"hash"}
          
from /nix/store/7hz0irlib58xlr2m40kb076hw24lnp6j-ruby3.2-dry-swagger-2.0.4/lib/ruby/gems/3.2.0/gems/dry-swagger-2.0.4/lib/dry/swagger/documentation_generator.rb:41:in `rescue in block in generate_documentation'
Caused by Dry::Swagger::Errors::MissingHashSchemaError: Dry::Swagger::Errors::MissingHashSchemaError
from /nix/store/7hz0irlib58xlr2m40kb076hw24lnp6j-ruby3.2-dry-swagger-2.0.4/lib/ruby/gems/3.2.0/gems/dry-swagger-2.0.4/lib/dry/swagger/documentation_generator.rb:99:in `generate_for_hash'
```

I wonder if there is a way this could support some sort of AnyValue?  
From my understanding, it's possible in openapi 3 to do:

```yaml
# openapi: 3.0.0
components:
  schemas:
    AnyValue: {}
```

And then use that.  
Is there maybe a way to support custom schemas in dry-swagger? Or am I using it wrong?

**Comment by pcboy** [comment]
I think I found a workaround by using `Types::Nominal::Any` :thinking: 


```ruby
require 'dry-types'
require 'dry-struct'

module Types
  include Dry.Types()
end

class Contracts::Sensors::NewContract < Dry::Validation::Contract
  params do
    required(:name).filled(:string)

    optional(:metadata).maybe(Types::Nominal::Any)
  end

  def to_swagger
    Dry::Swagger::DocumentationGenerator.new
                                        .from_validation(self.class)
                                        .tap do |x|
      x[:properties].merge!(
        metadata: {
          type: :object,
          properties: {},
          required: [],
          "x-nullable": true
        }
      )
    end
end
```

This seems to return:

```ruby
{
          :type => :object,
    :properties => {
            :name => {
                    :type => :string,
            :"x-nullable" => false
        },
        :metadata => {
                  :type => :object,
            :properties => {},
              :required => [],
            :"x-nullable" => true
        }
    },
      :required => [
        [0] :name
    ]
}
```

**Comment by Jane-Terziev** [comment]
Hi! Sorry for the late response.

You could use as you said, `Types::Nominal::Any` or `Types::Any ` for that.

You could also do manual overriding of the Parser result before sending it to the DocumentGenerator:

```ruby
def to_swagger
  fields_hash = ::DryValidationParser::ValidationSchemaParser.new
                                                             .call(self.class)
                                                             .keys
                                                             .except(:metadata) # remove the metadata field
  
  result = Dry::Swagger::DocumentationGenerator.new.generate_documentation(fields_hash)
  result[:properties][:metadata] = {} # add the doc for this specific field manually
end
```

If you need any help with anything else, feel free to leave a comment, i'll try to respond as soon as possible.

If everything is resolved, please close the issue.

Thanks for using the gem!

**Comment by pcboy** [comment]
Thanks @Jane-Terziev , I like your method too. :+1:
